trigger:
  - master
  - develop

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET sdk'
    inputs:
      packageType: 'sdk'
      version: '6.0.x'

  - task: DotNetCoreCLI@2
    displayName: "Pack"
    inputs:
      command: "pack"
      arguments: "--configuration $(buildConfiguration)"
      packagesToPack: "src/MonadExtensions/MonadExtensions.csproj"
      versioningScheme: "off"

  - task: NuGetCommand@2
    displayName: "Publish"
    inputs:
      command: "push"
      packagesToPush: "$(Build.ArtifactStagingDirectory)/*.nupkg"
      nuGetFeedType: "internal"
      publishVstsFeed: "mzelasko"
      versioningScheme: "off"
      allowPackageConflicts: true
