trigger:
  - master
  - develop

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: "Release"

steps:
  - task: DotNetCoreCLI@2
    displayName: "dotnet build"
    inputs:
      command: "build"
      arguments: "--configuration $(buildConfiguration)"
      projects: "CommonLib/CommonLib.csproj"

  - task: DotNetCoreCLI@2
    displayName: "dotnet pack"
    inputs:
      command: "pack"
      arguments: "--configuration $(buildConfiguration)"
      packagesToPack: "src/FunctionalExtensions/FunctionalExtensions.csproj"
      nobuild: true
      versioningScheme: "off"

  - task: NuGetCommand@2
    displayName: "nuget push"
    inputs:
      command: "push"
      feedsToUse: "select"
      packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg"
      nuGetFeedType: "internal"
      publishVstsFeed: "SharedFeed"
      versioningScheme: "off"
      allowPackageConflicts: true
